# Generated by Django 4.2 on 2023-04-07 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_season',
            field=models.CharField(choices=[('Primavera', 'Spring'), ('Verão', 'Summer'), ('Outono', 'Autumn'), ('Winter', 'Winter'), ('Não informado', 'Default')], default='Não informado', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
